services:
  web:
    build:
      context: ./server
      args:
        - UV_NO_DEV=0
    container_name: django_app
    environments:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=strongPassword
      - DB_HOST=db
      - PORT=5432
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
        restart: true

  db:
    image: postgres:18-trixie
    restart: always
    container_name: postgres_db
    environment:
      POSTGRES_PASSWORD: strongPassword
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
